name: linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        timeout-minutes: 90
        shell: bash
        run: |
          ./mvnw \
            --show-version --batch-mode --errors --no-transfer-progress \
            -DtrimStackTrace=false \
            -Dlog4j2.junit.fileCleanerSleepPeriodMillis=1000
